<?php
/**
 * Implements hook_init().
 */
function cu_emergency_banner_init() {
  drupal_add_js('https://embanner.univcomm.cornell.edu/OWC-emergency-banner.js', array('type' => 'external'));
  $test_banner = variable_get('cu_emergency_banner_check', FALSE);
  if ($test_banner) {
    $message = variable_get('cu_emergency_banner_text', t('The sky is falling!'));
    drupal_add_js("CUEmBanner.OWC_message = \"$message\"", array('type' => 'inline'));
  }
}

/**
 * form for administering emergency banner
 * @return form
 */
function cu_emergency_banner_admin() {
  $form = array();
  $form['cu_emergency_banner_check'] = array(
    '#type' => 'checkbox',
    '#title' => t('Display the Test Emergency Message'),
    '#default_value' => variable_get('cu_emergency_banner_check', FALSE),
  );
  $form['cu_emergency_banner_text'] = array(
    '#type' => 'textfield',
    '#title' => t('Test Emergency Message'),
    '#default_value' => variable_get('cu_emergency_banner_text', t('The sky is falling!')),
    '#size' => 30,
    '#maxlength' => 80,
    '#description' => t("Test message display to on your site."),
    '#required' => TRUE,
  );
  return system_settings_form($form);
}

/**
 * Implements hook_menu()
 * @return {array} callback info
 */
function cu_emergency_banner_menu() {
  $items = array();
  $items['admin/settings/cu_emergency_banner'] = array(
    'title' => 'Cornell Emergency Banner module settings',
    'description' => 'Provides a test of the banner.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cu_emergency_banner_admin'),
    'access arguments' => array('administer cu_emergency_banner settings'),
    'type' => MENU_NORMAL_ITEM,
   );
  return $items;
}

/**
 * Implements hook_permission
 * @return array permission structure
 */
function cu_emergency_banner_permission() {
  return array(
    'administer cu_emergency_banner settings' => array('title' => t('Administer CU Emergency Banner')),
    );
}
